# Generated by Django 6.0.6 on 2026-07-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
